# quality-security-ci.yml - GitHub Actions CI pipeline for quality and security scanning
# Supports: Trivy (container scanning), PHPStan (PHP analysis), SonarCloud (static analysis)
# Secrets stored in: AWS SSM Parameter Store

name: Quality & Security CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  AWS_REGION: us-east-1
  IMAGE_NAME: aw-bootcamp-app
  SONAR_ORGANIZATION: your-org
  SONAR_PROJECT_KEY: aw-bootcamp

jobs:
  # Job 1: PHP Static Analysis with PHPStan
  php-static-analysis:
    name: PHP Static Analysis
    runs-on: ubuntu-latest
    if: contains(join(filesModified('.'), ' '), '.php') || contains(join(filesModified('.'), ' '), 'composer.json'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, xml, gd

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse src --level=7 --no-progress

      - name: Upload PHPStan results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: phpstan-report
          path: phpstan-report/
          retention-days: 7

  # Job 2: SonarCloud Static Analysis
  sonarcloud-analysis:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: php-static-analysis
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
            -Dsonar.sources=src
            -Dsonar.language=php
            -Dsonar.phpCodesniffer.reportPath=report.xml
            -Dsonar.qualitygate.wait=true

  # Job 3: Container Scanning with Trivy
  container-security-scan:
    name: Container Security Scan
    runs-on: ubuntu-latest
    needs: [php-static-analysis, sonarcloud-analysis]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@v0.2.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'
          exit-code: '1'

      - name: Upload Trivy results
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: trivy-results.sarif

      - name: Display Trivy scan results
        if: always()
        run: |
          echo "Trivy scan completed"
          cat trivy-results.sarif | jq -r '.runs[0].results // [] | length' || echo "No issues found"

  # Job 4: Retrieve configuration from SSM (application deployment)
  retrieve-ssm-config:
    name: Retrieve SSM Configuration
    runs-on: ubuntu-latest
    needs: container-security-scan
    if: github.ref == 'refs/heads/main' && always()
    outputs:
      db_password: ${{ steps.ssm.outputs.db_password }}
      api_key: ${{ steps.ssm.outputs.api_key }}

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Retrieve SSM parameters
        id: ssm
        run: |
          DB_PASSWORD=$(aws ssm get-parameter --name "/aw-bootcamp/dev/database/password" --with-decryption --query "Parameter.Value" --output text)
          API_KEY=$(aws ssm get-parameter --name "/aw-bootcamp/dev/api/key" --with-decryption --query "Parameter.Value" --output text)
          echo "db_password=$DB_PASSWORD" >> $GITHUB_OUTPUT
          echo "api_key=$API_KEY" >> $GITHUB_OUTPUT
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          API_KEY: ${{ secrets.API_KEY }}

      - name: Verify configuration
        run: |
          echo "Database password retrieved: ${#DB_PASSWORD} characters"
          echo "API key retrieved: ${#API_KEY} characters"

  # Job 5: Quality Gate (all checks must pass)
  quality-gate:
    name: Quality Gate
    runs-on: ubuntu-latest
    needs: [php-static-analysis, sonarcloud-analysis, container-security-scan]
    if: always()

    steps:
      - name: Check quality gates
        run: |
          # Fail if any critical job failed
          if [[ "${{ needs.php-static-analysis.result }}" == "failure" ]]; then
            echo "❌ PHP Static Analysis failed"
            exit 1
          fi

          if [[ "${{ needs.sonarcloud-analysis.result }}" == "failure" ]]; then
            echo "❌ SonarCloud Quality Gate failed"
            exit 1
          fi

          if [[ "${{ needs.container-security-scan.result }}" == "failure" ]]; then
            echo "❌ Container Security Scan found critical vulnerabilities"
            exit 1
          fi

          echo "✅ All quality and security checks passed"
